WindowExposeEvent ![
x
    ^ x
].

WindowExposeEvent ![
x: anInteger
    x := anInteger
].

WindowExposeEvent ![
y
    ^ y
].

WindowExposeEvent ![
y: anInteger
    y := anInteger
].

WindowExposeEvent ![
width
    ^ width
].

WindowExposeEvent ![
width: anInteger
    width := anInteger
].

WindowExposeEvent ![
height
    ^ height
].

WindowExposeEvent ![
height: anInteger
    height := anInteger
].

WindowMouseButtonEvent ![
button
    ^ button
].

WindowMouseButtonEvent ![
button: anInteger
    button := anInteger
].

WindowMouseButtonEvent ![
x
    ^ x
].

WindowMouseButtonEvent ![
x: anInteger
    x := anInteger
].

WindowMouseButtonEvent ![
y
    ^ y
].

WindowMouseButtonEvent ![
y: anInteger
    y := anInteger
].

WindowMouseMotionEvent ![
buttons
    ^ buttons
].

WindowMouseMotionEvent ![
buttons: aSetOfButtons
    buttons := aSetOfButtons
].

WindowMouseMotionEvent ![
x
    ^ x
].

WindowMouseMotionEvent ![
x: anInteger
    x := anInteger
].

WindowMouseMotionEvent ![
y
    ^ y
].

WindowMouseMotionEvent ![
y: anInteger
    y := anInteger
].

WindowMouseMotionEvent ![
xrel
    ^ xrel
].

WindowMouseMotionEvent ![
xrel: anInteger
    xrel := anInteger
].

WindowMouseMotionEvent ![
yrel
    ^ yrel
].

WindowMouseMotionEvent ![
yrel: anInteger
    yrel := anInteger
].

WindowKeyboardEvent ![
scancode
    ^ scancode
].

WindowKeyboardEvent ![
scancode: anInteger
    scancode := anInteger
].

WindowKeyboardEvent ![
symbol
    ^ symbol
].

WindowKeyboardEvent ![
symbol: anInteger
    symbol := anInteger
].
